CREATE TABLE IF NOT EXISTS sequence_config (
    seq_name VARCHAR(64) NOT NULL PRIMARY KEY COMMENT '序列名称',
    max_id BIGINT NOT NULL DEFAULT 1 COMMENT '当前已分配的最大号段终点',
    step INT NOT NULL DEFAULT 1000 COMMENT '号段步长',
    increment_by INT NOT NULL DEFAULT 1 COMMENT '序列步长',
    min_value BIGINT NOT NULL DEFAULT 1 COMMENT '最小值',
    max_value BIGINT NOT NULL DEFAULT 9223372036854775807 COMMENT '最大值',
    cycle TINYINT NOT NULL DEFAULT 0 COMMENT '是否循环: 0-否, 1-是',
    mode VARCHAR(16) NOT NULL DEFAULT 'CACHED' COMMENT '序列模式: STRICT-严格连续, CACHED-号段缓存',
    start_with BIGINT NOT NULL DEFAULT 1 COMMENT '起始值(对应Oracle START WITH)',
    description VARCHAR(255) DEFAULT NULL COMMENT '描述',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='序列配置表';
